name: Deploy Moon on vps

on:
  push:
    branches: [ master ]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
      - name: Update remote repository
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASS }}
          source: "."
          target: "/home/silver/projects/moonbot/moonbot"

      # Runs a set of commands using the runners shell
      - name: Update moon docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          password: ${{ secrets.PASS }}
          script: |
            cd /home/silver/projects/moonbot
            docker rm -f moonbot || true 
            docker rmi $(docker images --filter=reference='silverliee/moonbot' --format "{{.ID}}")
            docker build . -t silverliee/moonbot
            docker run -d --name moonbot -p 8080:8080 silverliee/moonbot
            
            
